import { useEffect } from "react";
import Head from "next/head";

export default function Home() {
  useEffect(() => {
    console.log("Inicio");
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home</h1>
    </>
  );
}
